name: wine_app
description: A wine selection app to help you pick the best wine for any occasion or menu.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.1+2

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  image_picker: ^1.0.4
  google_ml_kit: ^0.16.3
  file_selector: ^1.0.1  # For desktop file picking support
  path_provider: ^2.1.1
  sqflite: ^2.3.0  # For local database to store wine information
  url_launcher: ^6.1.14  # For opening links to wine information
  # API services
  http: ^1.1.0  # For API calls
  share_plus: ^10.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_dotenv: ^5.1.0  # For loading environment variables
  google_mobile_ads: ^4.0.0  # For monetization with ads
  fluttertoast: ^8.2.2
  shared_preferences: ^2.0.18
  google_fonts: ^4.0.4
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - .env
  #   - images/a_dot_ham.jpeg

# Flutter launcher icons configuration
flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: true

dependency_overrides:
  file_selector_android: ^0.5.1+13